[package]
name = "eurypt_os"
version = "0.1.0"
authors = ["shorovatin"]
edition = "2018"

[dependencies]
bootloader = "0.9.3"
volatile = "0.2.6" #Needed for volatile wrapper (avoids compiler overoptimization)
spin = "0.5.2"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]